server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: resume-parser
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:eitc-sdt}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PWD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}
      init:
        pull-model-strategy: when_missing
      chat:
        model: llama3.2
  threads:
    virtual:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}

resume:
  bucket: ${RESUME_BUCKET:resume}

ocr:
  service:
    name: resume-ocr